package org.iutools.app

import android.content.Context
import androidx.compose.runtime.snapshots.SnapshotStateMap
import com.anthropic.client.okhttp.AnthropicOkHttpClient
import com.anthropic.errors.UnauthorizedException
import com.anthropic.models.messages.MessageCreateParams
import com.anthropic.models.messages.MessageParam
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/*
 * The "ask the AI to guess a word's meaning" mechanics: everything that
 * actually talks to Claude or the on-device model, independent of where it's
 * driven from. Shared by GuessMeaningSection (the inline flow on
 * WordLookupScreen -- the normal, single-screen experience for a real user,
 * see that file) and GuessMeaningScreen (the debug-only "Advanced" screen,
 * kept around for manual prompt-tuning with a full chat transcript). Both
 * read/write the same `conversations`/`modelStats` maps hoisted in
 * MainActivity, so either one can pick up where the other left off for a
 * given word -- switching to Advanced mid-attempt (or back) doesn't lose or
 * duplicate anything.
 */
private const val MODEL = "claude-haiku-4-5"
private const val MAX_TOKENS = 4096L

// The Anthropic SDK wraps every network-level failure (DNS, connection
// refused, timeout, TLS...) in an AnthropicIoException whose own message is
// always the same fixed "Request failed", with the actual reason only in
// its cause -- not useful on its own for telling "no internet" apart from
// anything else. Walks the full cause chain instead, so e.g. "Request
// failed" becomes "Request failed: Unable to resolve host ...".
private fun describeError(e: Throwable): String =
    generateSequence(e) { it.cause }
        .mapNotNull { it.message }
        .distinct()
        .joinToString(": ")
        .ifBlank { e.toString() }

data class GuessMeaningCacheKey(val word: String, val lenient: Boolean)

/**
 * Identifies one Guess Meaning "attempt" for caching purposes: everything
 * that can make the backend's answer differ. [word] is the word+lenient pair
 * WordLookupScreen already computes; [isLocalModel] the backend; [uiLanguage]
 * the in-app language active when the attempt was sent (chat_system_prompt
 * and the seed prompt are both localized, so a French and an English attempt
 * for the same word are genuinely different inputs, not just the same
 * request relabeled); [systemPrompt] and [seedMessage] the exact prompt text
 * used to start the conversation -- editable in the Advanced screen, so
 * different text is, for caching purposes, a different attempt worth keeping
 * separately, not overwriting or replaying a previous one.
 */
data class GuessMeaningConversationKey(
    val word: GuessMeaningCacheKey,
    val isLocalModel: Boolean,
    val uiLanguage: AppLanguage,
    val systemPrompt: String,
    val seedMessage: String,
)

data class ChatMessage(
    val role: MessageParam.Role,
    val text: String,
    val isError: Boolean = false,
    val latencyMs: Long? = null,
    val inputTokens: Long? = null,
    val outputTokens: Long? = null,
    // local-llm-spike branch: distinguishes a reply generated by the
    // on-device LiteRT-LM model from one generated by Claude, purely for
    // display (a different role label, and no input/output token counts).
    val isLocalModel: Boolean = false,
)

private class ClaudeCallResult(
    val text: String,
    val latencyMs: Long,
    val inputTokens: Long,
    val outputTokens: Long,
)

private suspend fun callClaude(history: List<ChatMessage>, systemPrompt: String, apiKey: String): ClaudeCallResult = withContext(Dispatchers.IO) {
    val client = AnthropicOkHttpClient.builder().apiKey(apiKey).build()
    val params = MessageCreateParams.builder()
        .model(MODEL)
        .maxTokens(MAX_TOKENS)
        .system(systemPrompt)
        .messages(history.map { MessageParam.builder().role(it.role).content(it.text).build() })
        .build()

    val startedAt = System.currentTimeMillis()
    val response = client.messages().create(params)
    val latencyMs = System.currentTimeMillis() - startedAt

    val text = response.content()
        .mapNotNull { it.text().orElse(null) }
        .joinToString("") { it.text() }

    ClaudeCallResult(
        text = text,
        latencyMs = latencyMs,
        inputTokens = response.usage().inputTokens(),
        outputTokens = response.usage().outputTokens(),
    )
}

internal object GuessMeaningEngine {
    /**
     * Appends [text] as a user turn to [history] and pushes the result to
     * [onMessagesChanged] immediately, then calls the chosen backend and
     * pushes the final (or, for the local model, each intermediate streamed)
     * state the same way. Doesn't return a value -- callers read the result
     * back out of wherever [onMessagesChanged] writes it (typically a
     * `conversations[key] = it` into the shared cache map), which is also
     * what makes a mid-attempt switch between the inline flow and the
     * Advanced screen safe: both write to that same map.
     */
    suspend fun send(
        context: Context,
        history: List<ChatMessage>,
        text: String,
        systemPrompt: String,
        useLocalModel: Boolean,
        // The user's own Claude.ai API key (see AppSettings.loadApiKey) --
        // ignored when useLocalModel is true. Callers are expected to have
        // already checked it's non-blank before calling send() at all (see
        // GuessMeaningSection's onNeedApiKey) -- an empty key here would
        // just fail the API call with an auth error, which still degrades
        // safely (see the UnauthorizedException branch below) but isn't the
        // intended path.
        apiKey: String,
        modelStats: SnapshotStateMap<String, AggregatedBackendStats>,
        unauthorizedErrorMessage: String,
        localModelMissingMessage: String,
        // "Erreur : %1$s" / "Error: %1$s" (see R.string.chat_error) -- any
        // failure that isn't the specific, already-localized cases above
        // (auth, missing local model) falls back to this, wrapping the raw
        // exception message (e.message, typically the underlying SDK/OkHttp
        // text, e.g. a network failure -- always in English, whatever the
        // in-app language) instead of showing it bare, per Alain's standing
        // requirement that nothing in the UI stays untranslated.
        genericErrorTemplate: String,
        onMessagesChanged: (List<ChatMessage>) -> Unit,
    ) {
        val trimmed = text.trim()
        if (trimmed.isEmpty()) return
        val historyWithNewMessage = history + ChatMessage(MessageParam.Role.USER, trimmed)
        onMessagesChanged(historyWithNewMessage)

        if (useLocalModel) {
            sendToLocalModel(
                context = context,
                historyWithNewMessage = historyWithNewMessage,
                userText = trimmed,
                systemPrompt = systemPrompt,
                modelStats = modelStats,
                localModelMissingMessage = localModelMissingMessage,
                genericErrorTemplate = genericErrorTemplate,
                onMessagesChanged = onMessagesChanged,
            )
            return
        }

        val updated = try {
            val result = callClaude(historyWithNewMessage, systemPrompt, apiKey)
            // MODEL (not just "Claude") is the stats key -- see ModelStats.kt
            // -- so a future switch to a different Claude model would track
            // separately too, same as local models do.
            modelStats[MODEL] = (modelStats[MODEL] ?: AggregatedBackendStats()) + BackendCallStats(
                latencyMs = result.latencyMs,
                inputTokens = result.inputTokens,
                outputTokens = result.outputTokens,
            )
            // See GuessMeaningCostTracker.kt -- same "only real calls, never
            // cache replays" reasoning as modelStats above.
            estimatedCostUsd(MODEL, result.inputTokens, result.outputTokens)?.let { costUsd ->
                GuessMeaningCostLog.record(context, MODEL, costUsd)
            }
            historyWithNewMessage + ChatMessage(
                role = MessageParam.Role.ASSISTANT,
                text = result.text,
                latencyMs = result.latencyMs,
                inputTokens = result.inputTokens,
                outputTokens = result.outputTokens,
            )
        } catch (e: UnauthorizedException) {
            // Covers an invalid, revoked, or expired key alike -- the API
            // returns the same 401 for all three, so there's no reliable way
            // (or need) to tell them apart here.
            historyWithNewMessage + ChatMessage(
                role = MessageParam.Role.ASSISTANT,
                text = unauthorizedErrorMessage,
                isError = true,
            )
        } catch (e: Exception) {
            historyWithNewMessage + ChatMessage(
                role = MessageParam.Role.ASSISTANT,
                text = genericErrorTemplate.format(describeError(e)),
                isError = true,
            )
        }
        onMessagesChanged(updated)
    }

    // Unlike the Claude path, the local path doesn't thread multi-turn
    // history into the model yet -- only [userText] (the latest turn) is
    // sent, not the full history. Fine for single-shot comparison, not yet a
    // real local chat (see the local-llm-spike doc, Phase 6).
    private suspend fun sendToLocalModel(
        context: Context,
        historyWithNewMessage: List<ChatMessage>,
        userText: String,
        systemPrompt: String,
        modelStats: SnapshotStateMap<String, AggregatedBackendStats>,
        localModelMissingMessage: String,
        genericErrorTemplate: String,
        onMessagesChanged: (List<ChatMessage>) -> Unit,
    ) {
        val modelFile = LocalLlmEngine.findModelFile(context)
        if (modelFile == null) {
            onMessagesChanged(
                historyWithNewMessage + ChatMessage(
                    role = MessageParam.Role.ASSISTANT,
                    text = localModelMissingMessage,
                    isError = true,
                ),
            )
            return
        }
        // The placeholder this index tracks is only ever updated in place
        // below (never removed/reordered), so the index stays valid for the
        // life of this call.
        val placeholderIndex = historyWithNewMessage.size
        var current = historyWithNewMessage + ChatMessage(MessageParam.Role.ASSISTANT, text = "", isLocalModel = true)
        onMessagesChanged(current)
        val startedAt = System.currentTimeMillis()
        // The model file's name is this backend's stats key (see
        // ModelStats.kt) -- distinguishes different local models tried in
        // the same session, since importModel() preserves the original
        // filename rather than renaming everything to one fixed name.
        val statsKey = modelFile.name
        var accumulated = ""
        try {
            LocalLlmEngine.generate(modelFile.absolutePath, systemPrompt, userText).collect { event ->
                when (event) {
                    is LocalGenerationEvent.Chunk -> {
                        accumulated += event.text
                        current = current.toMutableList().apply {
                            this[placeholderIndex] = ChatMessage(MessageParam.Role.ASSISTANT, text = accumulated, isLocalModel = true)
                        }
                        onMessagesChanged(current)
                    }
                    is LocalGenerationEvent.Done -> {
                        current = current.toMutableList().apply {
                            this[placeholderIndex] = ChatMessage(
                                role = MessageParam.Role.ASSISTANT,
                                text = accumulated,
                                latencyMs = System.currentTimeMillis() - startedAt,
                                inputTokens = event.prefillTokens.toLong(),
                                outputTokens = event.decodeTokens.toLong(),
                                isLocalModel = true,
                            )
                        }
                        onMessagesChanged(current)
                        modelStats[statsKey] = (modelStats[statsKey] ?: AggregatedBackendStats()) + BackendCallStats(
                            latencyMs = System.currentTimeMillis() - startedAt,
                            inputTokens = event.prefillTokens.toLong(),
                            outputTokens = event.decodeTokens.toLong(),
                        )
                    }
                }
            }
        } catch (e: Exception) {
            current = current.toMutableList().apply {
                this[placeholderIndex] = ChatMessage(
                    role = MessageParam.Role.ASSISTANT,
                    // Partial output generated before the failure, if any, is
                    // discarded here rather than kept alongside the error --
                    // simplest correct behavior; worth revisiting if partial
                    // local answers turn out to still be useful to see.
                    text = genericErrorTemplate.format(describeError(e)),
                    isError = true,
                    isLocalModel = true,
                )
            }
            onMessagesChanged(current)
        }
    }
}
