package org.iutools.app

import android.content.Context
import androidx.compose.runtime.snapshots.SnapshotStateMap
import com.anthropic.client.okhttp.AnthropicOkHttpClient
import com.anthropic.errors.UnauthorizedException
import com.anthropic.models.messages.MessageCreateParams
import com.anthropic.models.messages.MessageParam
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/*
 * The "ask the AI to guess a word's meaning" mechanics: everything that
 * actually talks to Claude, independent of where it's driven from. Shared by
 * GuessMeaningSection (the inline flow on WordLookupScreen -- the normal,
 * single-screen experience for a real user, see that file) and
 * ExplanationScreen's debug-only prompt resubmission. Both read/write the
 * same `conversations`/`modelStats` maps hoisted in MainActivity, so either
 * one can pick up where the other left off for a given word.
 *
 * An on-device backend (an alternative to the Claude call below) used to
 * live here too -- disabled per Alain's request, kept out-of-tree; see
 * composeApp/disabled-features/local-llm/README.md. useLocalModel below can
 * no longer be set true by any caller (nothing in the compiled app exposes a
 * toggle for it any more), but send() still checks it and refuses to
 * silently fall through to Claude if it ever is, rather than assuming the
 * disabled backend is gone.
 */
private const val MODEL = "claude-haiku-4-5"
private const val MAX_TOKENS = 4096L

// The Anthropic SDK wraps every network-level failure (DNS, connection
// refused, timeout, TLS...) in an AnthropicIoException whose own message is
// always the same fixed "Request failed", with the actual reason only in
// its cause -- not useful on its own for telling "no internet" apart from
// anything else. Walks the full cause chain instead, so e.g. "Request
// failed" becomes "Request failed: Unable to resolve host ...".
private fun describeError(e: Throwable): String =
    generateSequence(e) { it.cause }
        .mapNotNull { it.message }
        .distinct()
        .joinToString(": ")
        .ifBlank { e.toString() }

data class GuessMeaningCacheKey(val word: String, val lenient: Boolean)

/**
 * Identifies one Guess Meaning "attempt" for caching purposes: everything
 * that can make the backend's answer differ. [word] is the word+lenient pair
 * WordLookupScreen already computes; [isLocalModel] the backend (see this
 * file's header comment -- always `false` in the current build, kept so a
 * future reactivation of the on-device backend doesn't collide cache entries
 * with Claude ones for the same word); [uiLanguage] the in-app language
 * active when the attempt was sent (chat_system_prompt and the seed prompt
 * are both localized, so a French and an English attempt for the same word
 * are genuinely different inputs, not just the same request relabeled);
 * [systemPrompt] and [seedMessage] the exact prompt text used to start the
 * conversation -- editable from ExplanationScreen's "Inspecter le prompt",
 * so different text is, for caching purposes, a different attempt worth
 * keeping separately, not overwriting or replaying a previous one.
 */
data class GuessMeaningConversationKey(
    val word: GuessMeaningCacheKey,
    val isLocalModel: Boolean,
    val uiLanguage: AppLanguage,
    val systemPrompt: String,
    val seedMessage: String,
)

data class ChatMessage(
    val role: MessageParam.Role,
    val text: String,
    val isError: Boolean = false,
    val latencyMs: Long? = null,
    val inputTokens: Long? = null,
    val outputTokens: Long? = null,
    // Distinguishes a reply generated by the on-device backend from one
    // generated by Claude, purely for display (a different role label, and
    // no input/output token counts) -- always `false` in the current build
    // (see this file's header comment).
    val isLocalModel: Boolean = false,
)

private class ClaudeCallResult(
    val text: String,
    val latencyMs: Long,
    val inputTokens: Long,
    val outputTokens: Long,
)

private suspend fun callClaude(history: List<ChatMessage>, systemPrompt: String, apiKey: String): ClaudeCallResult = withContext(Dispatchers.IO) {
    val client = AnthropicOkHttpClient.builder().apiKey(apiKey).build()
    val params = MessageCreateParams.builder()
        .model(MODEL)
        .maxTokens(MAX_TOKENS)
        .system(systemPrompt)
        .messages(history.map { MessageParam.builder().role(it.role).content(it.text).build() })
        .build()

    val startedAt = System.currentTimeMillis()
    val response = client.messages().create(params)
    val latencyMs = System.currentTimeMillis() - startedAt

    val text = response.content()
        .mapNotNull { it.text().orElse(null) }
        .joinToString("") { it.text() }

    ClaudeCallResult(
        text = text,
        latencyMs = latencyMs,
        inputTokens = response.usage().inputTokens(),
        outputTokens = response.usage().outputTokens(),
    )
}

internal object GuessMeaningEngine {
    /**
     * Appends [text] as a user turn to [history] and pushes the result to
     * [onMessagesChanged] immediately, then calls Claude and pushes the
     * final state the same way. Doesn't return a value -- callers read the
     * result back out of wherever [onMessagesChanged] writes it (typically a
     * `conversations[key] = it` into the shared cache map), which is also
     * what makes a mid-attempt switch between the inline flow and
     * ExplanationScreen's prompt resubmission safe: both write to that same
     * map.
     */
    suspend fun send(
        context: Context,
        history: List<ChatMessage>,
        text: String,
        systemPrompt: String,
        // Always `false` from every current caller -- the on-device backend
        // this once selected is disabled (see this file's header comment).
        // Still checked below and refused rather than silently treated as
        // Claude, in case a future change starts passing `true` without
        // restoring that backend too.
        useLocalModel: Boolean,
        // The user's own Claude.ai API key (see AppSettings.loadApiKey).
        // Callers are expected to have already checked it's non-blank before
        // calling send() at all (see GuessMeaningSection's onNeedApiKey) --
        // an empty key here would just fail the API call with an auth error,
        // which still degrades safely (see the UnauthorizedException branch
        // below) but isn't the intended path.
        apiKey: String,
        modelStats: SnapshotStateMap<String, AggregatedBackendStats>,
        unauthorizedErrorMessage: String,
        // Shown instead of calling Claude when [useLocalModel] is `true` --
        // see R.string.local_llm_disabled_message. Not expected to ever be
        // seen in the current build, since nothing sets useLocalModel true.
        localModelDisabledMessage: String,
        // "Erreur : %1$s" / "Error: %1$s" (see R.string.chat_error) -- any
        // failure that isn't the specific, already-localized cases above
        // (auth) falls back to this, wrapping the raw exception message
        // (e.message, typically the underlying SDK/OkHttp text, e.g. a
        // network failure -- always in English, whatever the in-app
        // language) instead of showing it bare, per Alain's standing
        // requirement that nothing in the UI stays untranslated.
        genericErrorTemplate: String,
        onMessagesChanged: (List<ChatMessage>) -> Unit,
    ) {
        val trimmed = text.trim()
        if (trimmed.isEmpty()) return
        val historyWithNewMessage = history + ChatMessage(MessageParam.Role.USER, trimmed)
        onMessagesChanged(historyWithNewMessage)

        if (useLocalModel) {
            onMessagesChanged(
                historyWithNewMessage + ChatMessage(
                    role = MessageParam.Role.ASSISTANT,
                    text = localModelDisabledMessage,
                    isError = true,
                ),
            )
            return
        }

        val updated = try {
            val result = callClaude(historyWithNewMessage, systemPrompt, apiKey)
            // MODEL (not just "Claude") is the stats key -- see ModelStats.kt
            // -- so a future switch to a different Claude model would track
            // separately too, same as local models do.
            modelStats[MODEL] = (modelStats[MODEL] ?: AggregatedBackendStats()) + BackendCallStats(
                latencyMs = result.latencyMs,
                inputTokens = result.inputTokens,
                outputTokens = result.outputTokens,
            )
            // See GuessMeaningCostTracker.kt -- same "only real calls, never
            // cache replays" reasoning as modelStats above.
            estimatedCostUsd(MODEL, result.inputTokens, result.outputTokens)?.let { costUsd ->
                GuessMeaningCostLog.record(context, MODEL, costUsd)
            }
            historyWithNewMessage + ChatMessage(
                role = MessageParam.Role.ASSISTANT,
                text = result.text,
                latencyMs = result.latencyMs,
                inputTokens = result.inputTokens,
                outputTokens = result.outputTokens,
            )
        } catch (e: UnauthorizedException) {
            // Covers an invalid, revoked, or expired key alike -- the API
            // returns the same 401 for all three, so there's no reliable way
            // (or need) to tell them apart here.
            historyWithNewMessage + ChatMessage(
                role = MessageParam.Role.ASSISTANT,
                text = unauthorizedErrorMessage,
                isError = true,
            )
        } catch (e: Exception) {
            historyWithNewMessage + ChatMessage(
                role = MessageParam.Role.ASSISTANT,
                text = genericErrorTemplate.format(describeError(e)),
                isError = true,
            )
        }
        onMessagesChanged(updated)
    }
}
