"""
Mechanically generates lexc root entries from the source CSV data
(RootsSpalding.csv, RootsSchneider.csv,
Pronouns.csv, LoanWords.csv, UndecomposableCompositeWords.csv,
CommonCompositeWords.csv, WordsRelatedToRoots.csv, Locations.csv) --
roots are the "cheap", usually zero-phonology part of the lexicon (see
the plan's own discussion of where the real risk lives: affixes, not
roots), so unlike every affix added so far, these don't get
individually hand-verified against the source Kotlin analyzer --
verified instead by rerunning tools/fst/full_corpus_check.py afterward
and watching the histogram change, the same way :cli's own regression
gate works.

Locations.csv (place-name roots, e.g. "iqaluit", "arviat",
"sanikiluaq") was previously untouched by this script -- only
"nunavut" had ever been hand-added to lexicon.lexc directly, the same
one-at-a-time gap this script closes for the other root-source files.
Its "type" column is always "n" (matching ROOTS_CSV_TYPE_MAP's own
"n"->"Nouns"), and it shares the same column names (morpheme/nb/type/
combination/variant) load_roots_csv already reads for every other
source file, so no new parsing logic was needed -- skip_if_combination
is used here too (only 1 of its 203 rows has a non-empty
"combination", low risk either way, but consistent with the same
caution applied to CommonCompositeWords.csv/WordsRelatedToRoots.csv).
Its own "root"/"compositionRoot" columns (a demonstrative-style
"root that additionally takes a case ending" form, populated for 65 of
the 203 rows) are NOT used -- every place name is wired only as an
ordinary atomic noun root here, same treatment as every other source
file; if a gold word turns out to need the "root"-column form
specifically, that's a targeted follow-up, not guessed at now.

The last four files hold lexicalized composite/loan words (e.g. "piliriaq"
"program; item", "gavama" "government") -- several of these were hand-added
one at a time to lexicon.lexc when a specific gold word needed one
(minista, piliriaq, ilinniaq, akiraq, gavama, tusaaji); this script now
covers the same four files in bulk instead, same low-risk reasoning as
the original three. UndecomposableCompositeWords.csv's own name is
Benoit's explicit claim that its words are no longer decomposable today
even when a historical "combination" is on record.

CommonCompositeWords.csv/WordsRelatedToRoots.csv were ONCE filtered by
skip_if_combination (skip any row whose "combination" column is
non-empty, since e.g. "maligaq" is itself the surface result of
morphemes this project already implements, "malik"+"gaq" -- registering
it as ALSO an atomic root shadows, and can fully replace, the correct
compositional analysis). That filter was justified when first added (an
unfiltered attempt at the time pushed false positives from 2 to 18), but
re-tested against the much larger lexicon this project has grown into
since -- re-measured, not assumed still valid -- removing the filter now
gives zero regressions, +32 words, AND a lower false-positive count than
keeping it (91->69): most of these rows' "atomic root" reading no longer
competes with a real, fully-built compositional path the way it did
early on, so it just fills a gap instead of shadowing anything. Kept as
a `skip_if_combination` PARAMETER (not deleted) since the underlying
risk is real in principle, just currently negligible in practice -- flip
it back to True and re-measure if a future false positive turns out to
trace back to a specific "combination"-populated row shadowing a since-
completed compositional path.

Output is a SEPARATE file (roots-generated.lexc), never hand-edited, always
regenerated by rerunning this script -- mirrors this project's existing
convention for CSV-derived data (core/.../dataCSV/generated/, see AGENTS.md)
rather than mixing generated content into the hand-authored lexicon.lexc.

Scope of this first pass -- deliberately narrower than "every row":
  - Root type -> continuation lexicon, matching the hand-picked words
    already in lexicon.lexc: n->Nouns, v->Verbs, c->Conjunctions,
    e->Exclamations, a/p/rp/rpr->Adverbs/Pronouns (see
    load_roots_csv/load_pronouns_csv's own routing for how far these
    reach downstream).
  - Excludes RootsSpalding.csv's "pr" type (3 rows -- interrogative/
    indefinite pronoun-like roots, but a different code than Pronouns.csv's
    own "p"; not investigated yet, deferred rather than guessed at).
  - Excludes any row whose morpheme text contains "&" (26 rows in
    RootsSpalding.csv, e.g. "ak&a", "kallupi&&uk") -- an unexplained
    notation (also seen in tools/fst/affix-priority.md's "&iq/1nn" entry),
    not a real Inuktitut character; skipped rather than guessed at.
  - The "variant" column (alternate surface spellings, e.g. "arjaq"'s own
    variant "ajjaq") is emitted too, as additional entries sharing the
    same canonical+tag (162 rows across all 7 source files carry a
    variant). Space-separated multi-variant cells
    (e.g. "angirraq angiqraq") emit one entry per token, same "wire every
    literal spelling in parallel" treatment used throughout this project
    for hand-added variants.
  - Uses the canonical form for BOTH the analysis and (pre-phonology)
    surface side of each entry, same as every root added by hand so far --
    correct as long as the root itself needs no phonological alternation in
    isolation, which matches every hand-picked root confirmed so far.

Usage (from tools/fst/):
    python3 generate_roots.py
"""
import csv
import re
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent
DATA_DIR = REPO_ROOT / "core/src/commonMain/resources/org/iutools/linguisticdata/dataCSV"
OUTPUT_FILE = Path(__file__).parent / "roots-generated.lexc"

# type -> hand-authored lexicon this type's roots conceptually belong to.
# Generated entries live in a SEPARATELY NAMED lexicon ("<X>Generated"), not
# reused sublexicon names -- hfst-lexc refuses to compile the same LEXICON
# name defined in two different files ("Sublexicon defined more than once",
# confirmed by testing), so lexicon.lexc's `LEXICON Root` instead lists
# both "Nouns" (hand-picked) and "NounsGenerated" (this script's output) as
# separate entry points that converge on the same downstream continuation
# lexicons (NounContinuations etc.) below.
ROOTS_CSV_TYPE_MAP = {
    "n": "Nouns",
    "v": "Verbs",
    "c": "Conjunctions",
    "e": "Exclamations",
    "a": "Adverbs",
    "p": "Pronouns",
    "rp": "Pronouns",
    "rpr": "Pronouns",
}

# Generalizes generate_affixes.py's TRIGGER_LEXICON pattern (see that
# file's own comment) from "reached only after one specific morpheme id"
# to "reached only after a root in a specific CATEGORY". Suffixes.csv's
# "antipassive" condPrec (e.g. si/1vv's own condPrec="antipassive:si/1vv")
# means: this suffix may attach only after a root whose OWN "antipassive"
# column lists this suffix's id -- a category of ~250 roots, not one
# fixed id, so the id-trigger mechanism alone doesn't cover it. Measured
# against RootsSpalding.csv/RootsSchneider.csv before building this: 254
# roots have a non-empty antipassive value (usually "si/1vv" or "i/1vv",
# sometimes several space-separated values on one root), referencing 8
# distinct suffix ids -- only 6 of which are actually implemented
# suffixes with their own condPrec="antipassive:X" today (i/1vv, ji/1vv,
# ksi/1vv, nnik/1vv, ri/1vv, si/1vv); "nit/1vv"/"tsi/1vv"/"k&iq/1vv" are
# referenced by a handful of roots but aren't implemented suffixes at
# all, so skipped -- no lexicon to route them into. An HFST flag-
# diacritic approach (root sets a flag, suffix requires it) was tried
# first and abandoned after the toolchain wouldn't enforce it correctly
# in this HFST version (see project memory for the full debugging
# trail) -- this category-lexicon approach reuses the SAME mechanism
# already proven twice (Stage 1's hub audit, the li/4vv trigger), just
# generalized from "one id" to "any root with this antipassive value".
ANTIPASSIVE_LEXICON = {
    "si/1vv": "AfterApSiRoot",
    "i/1vv": "AfterApIRoot",
    "ji/1vv": "AfterApJiRoot",
    "ksi/1vv": "AfterApKsiRoot",
    "nnik/1vv": "AfterApNnikRoot",
    "ri/1vv": "AfterApRiRoot",
}

# Same category-trigger idea, for Suffixes.csv's condPrec="intransinfix:X"
# (self-referential: X's own row requires the preceding root's OWN
# "intransSuffix" CSV column to list X) -- e.g. gusuk/1vv's condPrec is
# EXACTLY "type:v,intransinfix:gusuk/1vv". Measured: 33 roots (all in
# RootsSpalding.csv; RootsSchneider.csv has none) have a non-empty
# intransSuffix value, referencing only 3 of the 4 suffixes that
# actually have their own condPrec="intransinfix:X" today (gusuk/1vv,
# ksaq/1vv, suk/1vv; si/3vv is referenced by exactly 1 root, "ilitaq").
INTRANSINFIX_LEXICON = {
    "gusuk/1vv": "AfterIntransGusukRoot",
    "ksaq/1vv": "AfterIntransKsaqRoot",
    "si/3vv": "AfterIntransSi3vvRoot",
    "suk/1vv": "AfterIntransSukRoot",
}

# Same idea again, for condPrec="transinfix:X" (the "transSuffix" CSV
# column). Measured: 217 roots have a non-empty transSuffix value, but
# only ONE actual suffix (gi/4vv, 54 matching roots) has its own
# condPrec="type:v,transinfix:gi/4vv" today -- "nil" (162 roots) and
# "ri/1vv" (1 root) don't match any implemented suffix's own condition,
# so nothing to route them into; skipped, not guessed at.
TRANSINFIX_LEXICON = {
    "gi/4vv": "AfterTransGi4vvRoot",
}

# NOT self-referential like the 3 above (the condition value is a fixed
# CATEGORY, "a" for adjective-like roots, not a specific suffix id) --
# gi/3vv, it/1vv, ksaq/2vv ALL share the exact same condPrec
# "type:v,nature:a", so all 3 route into the SAME lexicon, not one each.
# 243 roots have nature="a" in RootsSpalding.csv (RootsSchneider.csv:
# none of its own "a"-tagged rows -- only "zoo", unrelated).
NATURE_LEXICON = {
    "a": "AfterNatureARoot",
    # iqsuq/1nv ("to do a number of times") condPrec="nature:nb" -- 8
    # numeral roots (atausiq "one", marru "two", pingasu "three", ...).
    "nb": "AfterNatureNbRoot",
}


def is_clean_morpheme(morpheme: str) -> bool:
    return bool(morpheme) and "&" not in morpheme


# phonology.xfscript's general (unmarked) "j -> t || [t|k|q|r] _" rule
# (built for suffix-INITIAL j, e.g. juq/1vn's own j after a t/k/q/r-final
# stem) is blanket/context-blind -- it fires on ANY t/k/q/r immediately
# before a j in the FULLY COMPILED string, including a root's own
# INTERNAL spelling, not just at a morpheme boundary. Confirmed a real,
# fairly wide bug via "tikirarjuaq" (a Locations.csv place name):
# generating from tikirarjuaq+1n produced surface "tikirartuaq" -- the
# root's own internal "rj" silently corrupted to "rt". A scan of
# roots-generated.lexc found ~60 more root lines with the same
# t/k/q/r-before-j pattern (mostly the productive "-arjuaq"/"-arjuk"
# augmentative ending in place names), so this is systemic, not a
# one-off. JGUARD inserted here between the trigger consonant and "j"
# breaks the rule's required adjacency during composition (phonology.
# xfscript deletes JGUARD immediately after that one rule runs, once its
# job of blocking the match is done) -- root-internal consonant clusters
# are lexically fixed, never subject to this productive alternation, so
# protecting every root uniformly is correct, not a one-off patch.
_JGUARD_RE = re.compile(r"([tkqr])j")


def protect_internal_j(literal: str) -> str:
    return _JGUARD_RE.sub(r"\1JGUARDj", literal)


def load_roots_csv(filename: str, skip_if_combination: bool = False):
    """Yields (morpheme, nb, type) from a RootsSpalding.csv-shaped file.

    skip_if_combination: available for CommonCompositeWords.csv/
    WordsRelatedToRoots.csv but not currently passed as True by main()
    (see module docstring for why) -- these files record a word's own
    known decomposition in a "combination" column (e.g. "maligaq"'s is
    "malik/1v+gaq/1vn") without asserting the word is no longer analyzable
    that way, unlike UndecomposableCompositeWords.csv's own "combination"
    column, which is populated for words that file's own name already
    marks as permanently atomic. Registering "maligaq" as its own atomic
    root creates a second path to the exact same surface string as the
    real "malik"+"gaq" decomposition -- confirmed by testing that
    hfst-lookup then returns ONLY the atomic (wrong) reading for
    "maligait", not both -- so when this flag is set, any row whose
    "combination" is non-empty is skipped rather than risking that same
    shadowing for every other affix this project ever implements.
    Also yields each row's "variant" column (space-separated alternate
    surface spellings, e.g. "arjaq"'s own variant "ajjaq") as its own
    surface -- see main()'s use of this 4th field. RootsSpalding.csv's
    own "compositionRoot" column (when present -- only 4 rows have it,
    all the same shape: a "-t"-suffixed root like "atunit"/"qapsit"/
    "sitamat"/"tisamat" paired with the SAME word minus its trailing t)
    is merged into that same variant string -- gold treats "atuni" as a
    genuine free spelling variant of "atunit"/1n (identical canonical+tag,
    just a shorter surface), the same category as every hand-added root
    variant this project has needed, just already recorded in the CSV
    under a column this project hadn't read yet.

    An empty "nb" defaults to "1" rather than being skipped: confirmed
    across all 7 source files first (300 empty-nb rows total, zero of
    them sharing a (file, morpheme, type) triple with another empty-nb
    row), so defaulting can never create a same-file tag collision --
    "nb" numbers homograph senses starting at 1 everywhere else in this
    project's data, and an unnumbered single row is the same thing as
    row #1 of a series with no further entries.
    """
    path = DATA_DIR / filename
    with path.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            morpheme = row["morpheme"]
            nb = row["nb"].strip() or "1"
            root_type = row["type"]
            if root_type not in ROOTS_CSV_TYPE_MAP:
                continue
            if not is_clean_morpheme(morpheme):
                continue
            if skip_if_combination and row.get("combination"):
                continue
            variants = " ".join(
                v for v in (row.get("variant", ""), row.get("compositionRoot", "")) if v
            )
            yield (
                morpheme, nb, root_type, variants, row.get("antipassive", ""),
                row.get("intransSuffix", ""), row.get("transSuffix", ""),
                row.get("nature", ""),
            )


def load_pronouns_csv():
    """Pronouns.csv has a different column layout; type=='p' (ordinary
    pronoun root, e.g. "kikkut") and the "rp"/"rpr" "reduced pronoun"
    types (2 rows total: "ili"/1rp, "uva"/1rpr -- personal-pronoun
    stems that take their own dedicated tn-*-1s/1p endings, e.g.
    "uva"+"mnik"/tn-acc-s-1s = "uvannik") are handled here -- previously
    only "p" was, deferred for lack of investigation at the time; both
    are wired into the SAME "Pronouns" lexicon, since gold's own tag
    ("1rpr" etc.) already carries the type distinction, and the endings
    these roots need (mnik/mnut/ptingnik/ptingnut/ptingni's own
    -1s/-1p-tagged rows) turned out to already be bulk-generated by
    generate_affixes.py -- confirmed nothing else was missing before
    wiring this.
    """
    path = DATA_DIR / "Pronouns.csv"
    with path.open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            root_type = row["type"]
            if root_type not in ("p", "rp", "rpr"):
                continue
            morpheme = row["morpheme"]
            nb = row["nb"]
            if not is_clean_morpheme(morpheme) or not nb:
                continue
            yield morpheme, nb, root_type, row.get("variant", ""), "", "", "", ""


def main():
    entries_by_lexicon = {lex: [] for lex in set(ROOTS_CSV_TYPE_MAP.values())}
    tags_used = set()
    seen_entries = set()
    skipped = 0

    sources = [
        load_roots_csv("RootsSpalding.csv"),
        load_roots_csv("RootsSchneider.csv"),
        load_pronouns_csv(),
        load_roots_csv("LoanWords.csv"),
        load_roots_csv("UndecomposableCompositeWords.csv"),
        load_roots_csv("CommonCompositeWords.csv", skip_if_combination=False),
        load_roots_csv("WordsRelatedToRoots.csv", skip_if_combination=False),
        # skip_if_combination=False: re-tested the same way as
        # CommonCompositeWords.csv/WordsRelatedToRoots.csv above -- only
        # 10 of Locations.csv's rows even have a non-empty combination
        # column, and "ukiuqtaqtumi" needs one of them ("ukiuqtaqtuq",
        # place name for the Arctic) wired as its own atomic root despite
        # WordsRelatedToRoots-style etymology data existing for it.
        load_roots_csv("Locations.csv", skip_if_combination=False),
    ]
    for source in sources:
        for morpheme, nb, root_type, variant, antipassive, intranssuffix, transsuffix, nature in source:
            tag = f"+{nb}{root_type}"
            lexicon = ROOTS_CSV_TYPE_MAP[root_type]
            # NB: the hub lexicons in lexicon.lexc are "NounContinuations"/
            # "VerbContinuations" (singular), not "Nouns.../Verbs..." --
            # trailing "s" stripped to match.
            #
            # Adverbs/Pronouns route through NounContinuations too, not a
            # bare "#" alone: found via this session's own clustering
            # diagnostic (a graph-reachability BFS over gold's morpheme
            # chains) that ~20 gold words need an adverb or pronoun root
            # to take a FURTHER suffix or ending -- "kkut"/1nn ("qangakkut"),
            # QParticles' "li"/"lu" ("taimali"/"qanurli"), tn-* endings
            # ("ullumimut"), "u"/1nv ("mannaujuq"), "tuinnaq"/2nn
            # ("qanutuinnaq") among them -- not just standing bare, the
            # only thing ever wired before (same one-at-a-time gap already
            # hand-fixed individually for "maanna"/"qujannamiik"/
            # "taimanna" in lexicon.lexc, just never generalized to every
            # bulk-generated adverb/pronoun root). NounContinuations
            # already includes its own "#" (see that LEXICON block), so
            # this is a strict superset of the old bare-only reach, not
            # an addition alongside it -- confirmed the same "kikkutuinnait"
            # case this replaces (pronouns reaching NnSuffixes specifically)
            # still works, since NounContinuations ⊇ NnSuffixes.
            if lexicon in ("Adverbs", "Pronouns"):
                continuation = "NounContinuations"
                # The comment above claims QParticles' "li"/"lu" is already
                # covered via NounContinuations, but NounContinuations
                # never actually reaches QParticles (checked directly in
                # lexicon.lexc) -- confirmed a real gap via "maannali"/
                # "qanurli"/"taimaliqai" (adverb root + li/1q directly, no
                # noun/verb ending in between) failing the graph-
                # reachability diagnostic. Adding QParticles as a second,
                # PARALLEL continuation (not a replacement) fixes this
                # without narrowing the existing NounContinuations reach.
            elif lexicon in ("Conjunctions", "Exclamations"):
                # These don't get a *Continuations hub (only one onward
                # lexicon each, same as lexicon.lexc's hand-picked
                # "amma"/"ilaak" entries) -- QParticles directly, which
                # itself now also has its own "#" (see that LEXICON block).
                continuation = "QParticles"
            else:
                continuation = f"{lexicon.rstrip('s')}Continuations"

            continuations = [continuation]
            if lexicon in ("Adverbs", "Pronouns"):
                continuations.append("QParticles")
            if lexicon == "Verbs":
                for ap_value in antipassive.split(" "):
                    ap_lexicon = ANTIPASSIVE_LEXICON.get(ap_value)
                    if ap_lexicon and ap_lexicon not in continuations:
                        continuations.append(ap_lexicon)
                for it_value in intranssuffix.split(" "):
                    it_lexicon = INTRANSINFIX_LEXICON.get(it_value)
                    if it_lexicon and it_lexicon not in continuations:
                        continuations.append(it_lexicon)
                for tr_value in transsuffix.split(" "):
                    tr_lexicon = TRANSINFIX_LEXICON.get(tr_value)
                    if tr_lexicon and tr_lexicon not in continuations:
                        continuations.append(tr_lexicon)
                nat_lexicon = NATURE_LEXICON.get(nature.strip())
                if nat_lexicon and nat_lexicon not in continuations:
                    continuations.append(nat_lexicon)

            # A row's "variant" column records alternate surface spellings
            # of the SAME morpheme (e.g. "arjaq"'s own variant "ajjaq") --
            # space-separated when there's more than one. Emitted as
            # additional entries under the SAME canonical+tag, same
            # "different literal spellings, no collision since they're
            # different strings" treatment as every hand-added root
            # spelling variant this project has needed (taimait/issiva/
            # itsiva/missa/mitsa/niqsu/nirtu/niqtu/naammap/etc.) --
            # confirmed safe the same way: full_corpus_check.py catches
            # any actual collision.
            surfaces = [morpheme] + [
                v for v in variant.split(" ") if v and is_clean_morpheme(v)
            ]
            for surface in surfaces:
                for cont in continuations:
                    entry = f"{morpheme}{tag}:{protect_internal_j(surface)} {cont} ;"
                    if entry in seen_entries:
                        skipped += 1
                        continue
                    seen_entries.add(entry)
                    entries_by_lexicon[lexicon].append(entry)
                    tags_used.add(tag)

    entries_by_lexicon = {
        f"{lexicon}Generated": entries
        for lexicon, entries in entries_by_lexicon.items()
    }

    lines = []
    lines.append(
        "! Generated by tools/fst/generate_roots.py -- DO NOT HAND-EDIT.\n"
        "! Rerun that script to regenerate after the source CSVs change.\n"
        "! See its module docstring for exactly which rows are included/excluded.\n"
    )
    lines.append("Multichar_Symbols " + " ".join(sorted(tags_used)))
    for lexicon, entries in entries_by_lexicon.items():
        if not entries:
            continue
        lines.append(f"\nLEXICON {lexicon}")
        lines.extend(entries)

    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    total = sum(len(v) for v in entries_by_lexicon.values())
    print(f"Wrote {total} root entries ({len(tags_used)} distinct tags) to {OUTPUT_FILE}")
    print(f"Skipped {skipped} exact-duplicate entries")
    for lexicon, entries in entries_by_lexicon.items():
        print(f"  {lexicon}: {len(entries)}")


if __name__ == "__main__":
    main()
