package org.iutools.morph

/*
 * MorphologicalAnalyzer_FST's current outcomes on the "fair" Nunavut Hansard
 * gold standard -- the FST counterpart of MorphAnalCurrentExpectations_Hansard
 * (which records R2L's). The two analyzers cover the same words (917/919
 * present somewhere) but rank them differently, so a different set lands off
 * the top spot.
 *
 * GENERATED, not hand-curated: every line below is
 * MorphologicalAnalyzer_FST()'s actual outcome for that word, via the same
 * gold normalization MorphologicalAnalyzer_FST__AccuracyTest applies
 * (canonical morpheme + id only, "{atuaq/1v}" not "{atua:atuaq/1v}").
 * First-decomposition-correct: 671/919. Regenerate wholesale when the
 * transducer or the shared ranking changes -- do not edit a single word to
 * make the test pass.
 */
class MorphAnalCurrentExpectations_FST_Hansard : MorphAnalCurrentExpectationsAbstract() {

    override fun initMorphAnalCurrentExpectations() {

        //
        // Correct analysis is produced, but not as the top alternative.
        //
        expectFailure("aglattiu", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ajjigiinngittut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("akiraqtuqtut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("akulliq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("akunialuk", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("amisuni", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("amisunik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("amisunit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("amisunut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("amisuummata", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("amisuuningit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ammalu", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ammaluttauq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("apiqqusirijara", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("atuagait", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("atuagaq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("atuagarmik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("atuagarnik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("atuqtuksait", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("atuqtuksanut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("aulajjutinut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("aulaninginnut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("aulanirmut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("igluit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iglulirijikkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iglulirijirjuakkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iglulirinirmut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ikajuutit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iksivautaa", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ilaannikkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ilinniaqtinik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ilinniarviit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ilinniarvik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ilinniarvimmi", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ilinniarviup", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ilitaqsiniq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ilitarijauningit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("illuit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("illulirijikkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("illulirijirjuakkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("illulirinirmut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("illumi", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("illumik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("illunik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iluagut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iluani", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ilulingit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ilulingita", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("innatuqait", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("innatuqarnik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("innatuqarnut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("inulirijikkullu", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("inulirijikkunnut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("inulirijikkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("inuusilirijikkunullu", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iqalungni", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iqalunni", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iqalunnit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iqalunnut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iqqaqtuivilirijikkunnut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("iqqaqtuivilirijikkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("issivautaa", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("itsivautaa", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katilimaaqtugit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katillugit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimaji", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajilimaat", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajingannit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajinginnik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajinginnit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajinginnut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajingit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajingita", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajinut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiralaa", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiralaangit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiralaanguinnaqtut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiralaangukainnaqtunut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiralaani", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiralaanit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiralaanut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiralaat", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiujut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajiuqataujut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajjutiksait", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajjutiksanut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajjutiksaq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimajjutissaq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimaniq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimatillugit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimatuinnaqtillugit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimautiminingit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimautinik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimautitsa", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katimavimmi", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("katittugit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("kisumut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("kisunik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maannaujumi", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("mai", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("makkuttuit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligait", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaksait", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaksanit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaksaq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliriji", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligalirinirmut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqti", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtii", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtiit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtikkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtilimaanut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtilimaat", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtimut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtinik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtinit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtinut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtiujuq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtiujut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtiup", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtiuqatiga", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliuqtiuqatikka", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliurti", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliurtiit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaliurtiup", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maliganga", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligarmi", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligarmik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligarmut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligarnik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligarnit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligassait", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligassaq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligatsait", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligatsaq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaujuq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("maligaup", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("matuirutimut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ministaa", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ministau", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("naalautikkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("naammasaqtuit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("naammasaqtut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nanulik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("naukkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunaliit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalilimaat", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalinginni", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalingni", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalingnit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalingnut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalinni", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalinnik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalinnit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalinnu", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalinnut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunalittinni", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunaliujuni", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunaliujunik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunaliujunit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunaliujunut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunaliujuq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunaliujut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunavummiunut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("nunavummiut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pigiaqtitait", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pigiaqtitamut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pigiaqtitaq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pigiaqtitaujuq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pijjutigillugit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pijjutigillugu", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pijjutilik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pijjutiqaqtunik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pijjutiqaqtuq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pijjutiqaqtut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("piliriviit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pilirivinga", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pillugit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("piluaqtumi", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("piluaqtumik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("piluaqtumit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pinasuarusiulauqtumi", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pingasunik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pingasunit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("pingasunut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("qanuittuni", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("qanuittunik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("qautamaamut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("qautamaat", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("qujannamii", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("saniani", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("taanna", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("taiksumani", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("taissumani", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("taitsumani", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("tallimanut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("tamaani", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("timimigut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("timiujuq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("timiujut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("titiraqsimajunik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("titiraqsimajunut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("titiraqsimajut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("titiraqsimaningit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("titiraqti", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("titiraqtii", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("tukiliuqtausimajuq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("tullia", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("tungaagut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("ukunani", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("unnusakkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqalimaaqtauninga", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqalimaaqtauninginnut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqalimaaqtauningit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqalimaaqtauqullugu", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqalimaarniq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqalimaarvik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqartii", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausiit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausikkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausiksait", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausiksangit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausilirinirmut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausinga", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausingit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausiq", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausiqtigut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausirijanga", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausirmik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausirnik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausirnut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausissangit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausitsangit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqausituinnakkut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqsualuit", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqsualuk", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqsualummut", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uqsualuup", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uuktuutigilugu", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uuttuutigillugu", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uuttuutigilugu", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uvani", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uvannik", OutcomeType.CORRECT_NOT_FIRST)
        expectFailure("uvattinni", OutcomeType.CORRECT_NOT_FIRST)

        //
        // Some analyses are produced, but none is the correct one.
        //
        expectFailure("imaimmat", OutcomeType.CORRECT_NOT_PRESENT)
        expectFailure("taaksumunga", OutcomeType.CORRECT_NOT_PRESENT)

        //
        // No decomposition produced at all: none.
        //
    }
}
